### PR TITLE
add check_format and use it in ci

### PR DESCRIPTION
**Pull request by jchavarri**
tiny, tiny thing :)

### CODE REVIEW

**Comment by tmattio** [comment]
LGTM!
Although I'm curious: do you have a use case for this command? `dune build --root . --auto-promote @fmt` also exits with a non-zero code, so the CI/CD should fail correctly with it.

**Review by tmattio — APPROVED** [review]

**Comment by jchavarri** [comment]
Oh, I thought promoting would always succeed. 😅 

If that's not the case, I'm not sure if this change makes a lot of sense. I guess mostly the guarantee that CI disk remains untouched...

**Comment by tmattio** [comment]
> the guarantee that CI disk remains untouched

Good point! If that's only going to be used in the CI, maybe we don't need to have it in the Makefile then. I'm good with the change either way, your call 🙂

**Comment by jchavarri** [comment]
Tbh, I don't think any change makes a difference and they just add noise, considering I had the wrong idea from the beginning 😄 👍 Closing!

**Pull request closed without merging**
